### ISSUE TITLE
Question: what is the firmware-tag-2021.01.zip useful for?

### ISSUE THREAD

**Issue by santiagorg2401** [bitcraze/crazyflie-release#4]
Hi, 
I have a question regarding the firmware, when uploading the firmware to the Crazyflie I suppose one have to use the firmware-cf2-2021.01.zip file, but then, for what is firmware-tag-2021.01.zip used?
Thank you in advance,
S. Restrepo.

**Comment by krichardsson** [comment]
Hi, 
there are two flavours of the firmware that we call platforms: "cf2" and "tag". Cf2 is used for flying devices like the Crazyflie and Tag is currently only used for the Roadrunner

**Comment by santiagorg2401** [comment]
Thank you for answering, I appreciate it, I understand now.

**Comment by krichardsson** [comment]
I updated the readme to make it clearer
